#!/bin/bash

# ============================================================================
# SCRIPT: Comandos para Implementar Sincronización de Profesionales
# ============================================================================
# Ejecuta estos comandos en orden para completar la implementación

echo "==============================================="
echo "Implementación: Sincronización de Profesionales"
echo "==============================================="
echo ""

# PASO 1: Aplicar Migración SQL
echo "PASO 1: Aplicar Migración SQL"
echo "---"
echo "Opción 1 (Supabase CLI):"
echo "  supabase db push"
echo ""
echo "Opción 2 (MCP):"
echo "  npm run apply-migrations:mcp"
echo ""
echo "Opción 3 (Manual en dashboard Supabase):"
echo "  1. Ir a: https://app.supabase.com/project/abxusmjvsuabvbbwwxqg/sql/new"
echo "  2. Copiar contenido de: supabase/migrations/20250129_001_extend_hosix_usuarios_profesionales.sql"
echo "  3. Ejecutar"
echo ""
echo "✓ Presione Enter cuando haya completado este paso..."
read

# PASO 2: Regenerar Tipos TypeScript
echo ""
echo "PASO 2: Regenerar Tipos TypeScript"
echo "---"
echo "Ejecute uno de estos comandos:"
echo ""
echo "Opción 1 (Supabase CLI):"
echo "  supabase gen types typescript --schema public > src/integrations/supabase/types.ts"
echo ""
echo "Opción 2 (MCP):"
echo "  npm run setup-mcp"
echo ""
echo "✓ Presione Enter cuando haya completado este paso..."
read

# PASO 3: Configurar Variables de Entorno
echo ""
echo "PASO 3: Agregar Variables de Entorno"
echo "---"
echo "Agregar a .env o .env.renaprosa:"
echo ""
echo "VITE_RENAPROSA_SUPABASE_URL=https://wdieynendfjbkbhfovrx.supabase.co"
echo "VITE_RENAPROSA_SUPABASE_ANON_KEY=sb_publishable_9KoyZtFgO79lLad"
echo ""
echo "✓ Presione Enter cuando haya completado este paso..."
read

# PASO 4: Agregar Ruta de Login
echo ""
echo "PASO 4: Agregar Ruta de Login de Profesional"
echo "---"
echo "Editar: src/routes/AppRouter.tsx (o donde tengas las rutas)"
echo ""
echo "Agregar:"
echo "  import ProfesionalLogin from '@/pages/Hosix/ProfesionalLogin'"
echo ""
echo "  {"
echo "    path: '/hosix/profesional-login',"
echo "    element: <ProfesionalLogin />"
echo "  }"
echo ""
echo "✓ Presione Enter cuando haya completado este paso..."
read

# PASO 5: Integrar Componente en Panel Admin
echo ""
echo "PASO 5: Integrar ProfesionalSyncManager en Panel"
echo "---"
echo "Editar: src/pages/Hosix/Configuracion.tsx (o panel del director)"
echo ""
echo "Importar:"
echo "  import ProfesionalSyncManager from '@/components/hosix/ProfesionalSyncManager'"
echo ""
echo "Agregar en pantalla (ejemplo):"
echo "  <Tab value='profesionales'>"
echo "    <ProfesionalSyncManager />"
echo "  </Tab>"
echo ""
echo "✓ Presione Enter cuando haya completado este paso..."
read

# PASO 6: Verificación Final
echo ""
echo "PASO 6: Verificación Final"
echo "---"
echo "✓ Migrations aplicadas"
echo "✓ Tipos regenerados"
echo "✓ Variables de entorno configuradas"
echo "✓ Rutas agregadas"
echo "✓ Componentes integrados"
echo ""

# PASO 7: Testing
echo ""
echo "PASO 7: Pruebas Recomendadas"
echo "---"
echo "1. Iniciar servidor de desarrollo:"
echo "   npm run dev"
echo ""
echo "2. Probar login normal:"
echo "   Ir a: http://localhost:5173/hosix/login"
echo "   Usar credenciales de director"
echo ""
echo "3. Acceder a panel de sincronización:"
echo "   http://localhost:5173/hosix/configuracion"
echo "   Ir a tab 'Profesionales'"
echo ""
echo "4. Hacer click en 'Sincronizar Ahora'"
echo "   Observar:"
echo "   - Barra de progreso"
echo "   - Profesionales insertados/actualizados"
echo "   - Tabla con nuevos profesionales"
echo ""
echo "5. Probar login de profesional:"
echo "   Ir a: http://localhost:5173/hosix/profesional-login"
echo "   Usar un ID profesional sincronizado"
echo "   Usar contraseña generada (id_profesional + '123456')"
echo ""
echo "6. Cambiar contraseña:"
echo "   Sistema debe forzar cambio en primer login"
echo "   Ingresar nueva contraseña (8+ caracteres)"
echo ""
echo "✓ Presione Enter para continuar..."
read

# PASO 8: Comandos Útiles
echo ""
echo "COMANDOS ÚTILES:"
echo "---"
echo ""
echo "Ver estado de migraciones:"
echo "  supabase migration list"
echo ""
echo "Regenerar tipos (solo tipos):"
echo "  supabase gen types typescript --schema public > src/integrations/supabase/types.ts"
echo ""
echo "Limpiar cache de npm:"
echo "  npm run dev -- --force"
echo ""
echo "Ver logs en Supabase:"
echo "  https://app.supabase.com/project/abxusmjvsuabvbbwwxqg/logs"
echo ""

echo ""
echo "==============================================="
echo "✓ Implementación Completada"
echo "==============================================="
echo ""
echo "Archivos creados:"
echo "  ✓ supabase/migrations/20250129_001_extend_hosix_usuarios_profesionales.sql"
echo "  ✓ src/hooks/useProfesionalAuth.ts"
echo "  ✓ src/hooks/useProfesionalesSync.ts"
echo "  ✓ src/pages/Hosix/ProfesionalLogin.tsx"
echo "  ✓ src/components/hosix/ProfesionalSyncManager.tsx"
echo ""
echo "Documentación:"
echo "  ✓ ARQUITECTURA_SINCRONIZACION_PROFESIONALES.md"
echo "  ✓ IMPLEMENTACION_RESUMEN.md"
echo "  ✓ GET_ESTRUCTURA_DATOS.md"
echo "  ✓ TIPOS_ACTUALIZACION.md"
echo "  ✓ COMANDOS_IMPLEMENTACION.sh"
echo ""
echo "==============================================="
