# DHIS2 configuration for Docker Compose
connection.dialect=org.hibernate.dialect.PostgreSQL13Dialect
connection.driver_class=org.postgresql.Driver
connection.url=jdbc:postgresql://db:5432/dhis2
connection.username=dhis2
connection.password=dhis2pass
connection.schema=public

server.https=false
server.port=8080
server.base_url=http://localhost:8080/dhis2

instance.default_locale=es_ES
instance.default_ui_locale=es_ES
instance.org_unit_levels=4

mail.protocol=smtp
mail.host=smtp.gmail.com
mail.port=587
mail.from=epidemiologia@minsalud.gq
